x-db-access: &db-access
  environment:
    POSTGRES_USER_FILE: /run/secrets/postgres_chat_login
    POSTGRES_HOST_FILE: /run/secrets/postgres_chat_host_name
    POSTGRES_PASSWORD_FILE: /run/secrets/postgres_chat_password
    POSTGRES_DB_FILE: /run/secrets/postgres_chat_db_name
  secrets:
    - postgres_chat_db_name
    - postgres_chat_login
    - postgres_chat_password
    - postgres_chat_host_name
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
  llm_chat_db:
    <<: *db-access
    image: postgres:13
    container_name: llm_chat_db
    healthcheck:
      test : ["CMD-SHELL", "sh -c 'pg_isready -U $$(cat /run/secrets/postgres_chat_login) -d $$(cat /run/secrets/postgres_chat_db_name)'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
    - "5434:5434"
    volumes:
     - postgres_chat_data:/var/lib/postgresql/data
  ollama:
    build:
      context: .
      dockerfile : src/ollama/Dockerfile
    container_name: ollama
    tty: true  
    healthcheck:
      test: ["CMD-SHELL", "ollama list | grep -q 'llama3' && ollama list | grep -q 'nomic-embed-text'"]
      interval: 15s    
      timeout: 5s       
      retries: 40       
      start_period: 10s
    ports:
     - '11434:11434'
    volumes:
     - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    dns:
      - 8.8.8.8
      - 1.1.1.1
  llm_ml_worker:
    <<: *db-access
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      llm_redis:
        condition: service_healthy
    volumes:
     - .:/files
    entrypoint: ["celery", "-A", "src.worker.celery_app", "worker", "--loglevel=info"]
  llm_redis:
    image: redis:8.6-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$( cat /run/secrets/redis_password) ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
     - '6377:6379'
    command: sh -c "redis-server --save 20 1 --loglevel notice --requirepass $$(cat /run/secrets/redis_password) --appendonly yes --maxmemory-policy volatile-ttl --maxmemory 512mb"
    secrets:
     - redis_password
    volumes:
     - redis:/data 
  llm_api:
    <<: *db-access
    build:
      context: .
      dockerfile: src/Dockerfile 
    container_name: llm_api
    depends_on:                     
      llm_chat_db:                  
        condition: service_healthy
      ollama:
        condition: service_healthy  
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - .:/files
    command:
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
secrets:
  redis_password:
    file: ./secrets/redis_password.txt
  postgres_chat_db_name:
    file: ./secrets/postgres_chat_db_name.txt
  postgres_chat_login:
    file: ./secrets/postgres_chat_login.txt
  postgres_chat_password:
    file: ./secrets/postgres_chat_password.txt
  postgres_chat_host_name:
    file: ./secrets/postgres_chat_host_name.txt
volumes:
  redis:
  ollama_data:
  postgres_chat_data:
  files:
configs:
  qdrant_config:
    content: |
      log_level: INFO