"""Cascade deleting

Revision ID: 1d2994259ee3
Revises: 62b0a2ffbba6
Create Date: 2026-03-12 15:23:57.349689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2994259ee3'
down_revision: Union[str, Sequence[str], None] = '62b0a2ffbba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('message_chat_id_fkey'), 'message', type_='foreignkey')
    op.drop_constraint(op.f('message_user_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_chat_user_id_fkey'), 'user_chat', type_='foreignkey')
    op.drop_constraint(op.f('user_chat_chat_id_fkey'), 'user_chat', type_='foreignkey')
    op.create_foreign_key(None, 'user_chat', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_chat', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_chat', type_='foreignkey')
    op.drop_constraint(None, 'user_chat', type_='foreignkey')
    op.create_foreign_key(op.f('user_chat_chat_id_fkey'), 'user_chat', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('user_chat_user_id_fkey'), 'user_chat', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_user_id_fkey'), 'message', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('message_chat_id_fkey'), 'message', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###
