"""Adding chat structure

Revision ID: 62b0a2ffbba6
Revises: 56c2a9373d0a
Create Date: 2026-03-11 12:35:43.618158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b0a2ffbba6'
down_revision: Union[str, Sequence[str], None] = '56c2a9373d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('tokens_count', sa.Integer(), nullable=False))
    op.drop_column('message', 'tokens_counbt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('tokens_counbt', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('message', 'tokens_count')
    # ### end Alembic commands ###
